// ── Fleet Data — TakeMe Mobility EV Rental Fleet ───────────────────────────
// Real EPA ranges, 0-60 times, cargo volumes, and premium rental pricing.

export interface Vehicle {
  key: string;
  brand: string;
  name: string;
  category: 'sedan' | 'suv' | 'truck' | 'luxury' | 'performance';
  dailyRate: number;
  weeklyRate: number;
  rangeEpa: number;
  seats: number;
  cargo: string;
  chargingSpeed: string;
  zerotoSixty: string;
  features: string[];
  image: null;
}

export interface FleetFilters {
  category?: string;
  brand?: string;
  priceRange?: 'low' | 'mid' | 'high';
  minSeats?: number;
  search?: string;
}

// ── Fleet ───────────────────────────────────────────────────────────────────

export const FLEET: Vehicle[] = [
  // ─── Tesla ──────────────────────────────────────────────────────────────
  {
    key: 'tesla-model-3-standard',
    brand: 'Tesla',
    name: 'Model 3 Standard Range',
    category: 'sedan',
    dailyRate: 89,
    weeklyRate: 490,
    rangeEpa: 272,
    seats: 5,
    cargo: '23 cu ft',
    chargingSpeed: '250 kW DC',
    zerotoSixty: '5.8s',
    features: ['Autopilot', '15" touchscreen', 'Glass roof'],
    image: null,
  },
  {
    key: 'tesla-model-3-lr',
    brand: 'Tesla',
    name: 'Model 3 Long Range',
    category: 'sedan',
    dailyRate: 99,
    weeklyRate: 545,
    rangeEpa: 358,
    seats: 5,
    cargo: '23 cu ft',
    chargingSpeed: '250 kW DC',
    zerotoSixty: '4.2s',
    features: ['Autopilot', 'Dual motor AWD', 'Premium audio'],
    image: null,
  },
  {
    key: 'tesla-model-3-performance',
    brand: 'Tesla',
    name: 'Model 3 Performance',
    category: 'performance',
    dailyRate: 119,
    weeklyRate: 655,
    rangeEpa: 315,
    seats: 5,
    cargo: '23 cu ft',
    chargingSpeed: '250 kW DC',
    zerotoSixty: '3.1s',
    features: ['Track Mode', 'Performance brakes', 'Carbon fiber spoiler'],
    image: null,
  },
  {
    key: 'tesla-model-y-standard',
    brand: 'Tesla',
    name: 'Model Y Standard Range',
    category: 'suv',
    dailyRate: 99,
    weeklyRate: 545,
    rangeEpa: 283,
    seats: 5,
    cargo: '76 cu ft',
    chargingSpeed: '250 kW DC',
    zerotoSixty: '5.0s',
    features: ['Autopilot', 'Power liftgate', 'Flat-fold seats'],
    image: null,
  },
  {
    key: 'tesla-model-y-lr',
    brand: 'Tesla',
    name: 'Model Y Long Range',
    category: 'suv',
    dailyRate: 109,
    weeklyRate: 600,
    rangeEpa: 330,
    seats: 7,
    cargo: '76 cu ft',
    chargingSpeed: '250 kW DC',
    zerotoSixty: '4.8s',
    features: ['Autopilot', '7-seat option', 'Tow package'],
    image: null,
  },
  {
    key: 'tesla-model-y-performance',
    brand: 'Tesla',
    name: 'Model Y Performance',
    category: 'performance',
    dailyRate: 129,
    weeklyRate: 710,
    rangeEpa: 303,
    seats: 5,
    cargo: '76 cu ft',
    chargingSpeed: '250 kW DC',
    zerotoSixty: '3.5s',
    features: ['Track Mode', 'Performance brakes', '21" Uberturbine wheels'],
    image: null,
  },
  {
    key: 'tesla-model-s-standard',
    brand: 'Tesla',
    name: 'Model S',
    category: 'luxury',
    dailyRate: 149,
    weeklyRate: 820,
    rangeEpa: 405,
    seats: 5,
    cargo: '28 cu ft',
    chargingSpeed: '250 kW DC',
    zerotoSixty: '3.1s',
    features: ['Yoke steering', '17" cinematic display', 'Air suspension'],
    image: null,
  },
  {
    key: 'tesla-model-s-plaid',
    brand: 'Tesla',
    name: 'Model S Plaid',
    category: 'performance',
    dailyRate: 199,
    weeklyRate: 1095,
    rangeEpa: 396,
    seats: 5,
    cargo: '28 cu ft',
    chargingSpeed: '250 kW DC',
    zerotoSixty: '1.99s',
    features: ['Tri-motor', '200 mph top speed', 'Carbon ceramic brakes'],
    image: null,
  },
  {
    key: 'tesla-model-x-standard',
    brand: 'Tesla',
    name: 'Model X',
    category: 'luxury',
    dailyRate: 169,
    weeklyRate: 930,
    rangeEpa: 348,
    seats: 7,
    cargo: '91 cu ft',
    chargingSpeed: '250 kW DC',
    zerotoSixty: '3.8s',
    features: ['Falcon wing doors', '7-seat config', 'HEPA filtration'],
    image: null,
  },
  {
    key: 'tesla-model-x-plaid',
    brand: 'Tesla',
    name: 'Model X Plaid',
    category: 'performance',
    dailyRate: 219,
    weeklyRate: 1205,
    rangeEpa: 326,
    seats: 7,
    cargo: '91 cu ft',
    chargingSpeed: '250 kW DC',
    zerotoSixty: '2.5s',
    features: ['Tri-motor', 'Falcon wing doors', '1,020 hp'],
    image: null,
  },
  {
    key: 'tesla-cybertruck-awd',
    brand: 'Tesla',
    name: 'Cybertruck AWD',
    category: 'truck',
    dailyRate: 179,
    weeklyRate: 985,
    rangeEpa: 318,
    seats: 5,
    cargo: '68 cu ft bed',
    chargingSpeed: '250 kW DC',
    zerotoSixty: '4.1s',
    features: ['Exoskeleton body', 'Vault bed', 'Air suspension'],
    image: null,
  },
  {
    key: 'tesla-cybertruck-cyberbeast',
    brand: 'Tesla',
    name: 'Cybertruck Cyberbeast',
    category: 'performance',
    dailyRate: 229,
    weeklyRate: 1260,
    rangeEpa: 301,
    seats: 5,
    cargo: '68 cu ft bed',
    chargingSpeed: '250 kW DC',
    zerotoSixty: '2.6s',
    features: ['Tri-motor', '845 hp', 'Stainless exoskeleton'],
    image: null,
  },

  // ─── Rivian ─────────────────────────────────────────────────────────────
  {
    key: 'rivian-r1t-adventure',
    brand: 'Rivian',
    name: 'R1T Adventure',
    category: 'truck',
    dailyRate: 179,
    weeklyRate: 985,
    rangeEpa: 328,
    seats: 5,
    cargo: '62 cu ft bed',
    chargingSpeed: '220 kW DC',
    zerotoSixty: '3.5s',
    features: ['Gear tunnel', 'Camp kitchen option', 'Quad motor'],
    image: null,
  },
  {
    key: 'rivian-r1t-max',
    brand: 'Rivian',
    name: 'R1T Max Pack',
    category: 'truck',
    dailyRate: 209,
    weeklyRate: 1150,
    rangeEpa: 410,
    seats: 5,
    cargo: '62 cu ft bed',
    chargingSpeed: '220 kW DC',
    zerotoSixty: '3.0s',
    features: ['Max battery', '400+ mi range', 'Quad motor AWD'],
    image: null,
  },
  {
    key: 'rivian-r1s-adventure',
    brand: 'Rivian',
    name: 'R1S Adventure',
    category: 'suv',
    dailyRate: 169,
    weeklyRate: 930,
    rangeEpa: 321,
    seats: 7,
    cargo: '104 cu ft',
    chargingSpeed: '220 kW DC',
    zerotoSixty: '3.6s',
    features: ['3-row seating', 'Air suspension', 'Off-road capable'],
    image: null,
  },
  {
    key: 'rivian-r1s-max',
    brand: 'Rivian',
    name: 'R1S Max Pack',
    category: 'suv',
    dailyRate: 199,
    weeklyRate: 1095,
    rangeEpa: 400,
    seats: 7,
    cargo: '104 cu ft',
    chargingSpeed: '220 kW DC',
    zerotoSixty: '2.9s',
    features: ['Max battery', 'Quad motor', '3-row luxury'],
    image: null,
  },

  // ─── BMW ────────────────────────────────────────────────────────────────
  {
    key: 'bmw-i4-edrive35',
    brand: 'BMW',
    name: 'i4 eDrive35',
    category: 'sedan',
    dailyRate: 119,
    weeklyRate: 655,
    rangeEpa: 260,
    seats: 5,
    cargo: '18 cu ft',
    chargingSpeed: '180 kW DC',
    zerotoSixty: '5.6s',
    features: ['iDrive 8', 'Curved display', 'Sport seats'],
    image: null,
  },
  {
    key: 'bmw-i4-edrive40',
    brand: 'BMW',
    name: 'i4 eDrive40',
    category: 'sedan',
    dailyRate: 129,
    weeklyRate: 710,
    rangeEpa: 301,
    seats: 5,
    cargo: '18 cu ft',
    chargingSpeed: '200 kW DC',
    zerotoSixty: '5.5s',
    features: ['iDrive 8', 'HUD', 'Harman Kardon audio'],
    image: null,
  },
  {
    key: 'bmw-i4-m50',
    brand: 'BMW',
    name: 'i4 M50',
    category: 'performance',
    dailyRate: 159,
    weeklyRate: 875,
    rangeEpa: 270,
    seats: 5,
    cargo: '18 cu ft',
    chargingSpeed: '200 kW DC',
    zerotoSixty: '3.7s',
    features: ['M Sport suspension', 'Dual motor AWD', '536 hp'],
    image: null,
  },
  {
    key: 'bmw-i5-edrive40',
    brand: 'BMW',
    name: 'i5 eDrive40',
    category: 'sedan',
    dailyRate: 149,
    weeklyRate: 820,
    rangeEpa: 295,
    seats: 5,
    cargo: '15 cu ft',
    chargingSpeed: '205 kW DC',
    zerotoSixty: '5.4s',
    features: ['Theater screen', 'Air suspension', 'Parking assist'],
    image: null,
  },
  {
    key: 'bmw-i5-m60',
    brand: 'BMW',
    name: 'i5 M60',
    category: 'performance',
    dailyRate: 189,
    weeklyRate: 1040,
    rangeEpa: 256,
    seats: 5,
    cargo: '15 cu ft',
    chargingSpeed: '205 kW DC',
    zerotoSixty: '3.7s',
    features: ['M adaptive suspension', 'Dual motor 593 hp', 'Executive lounge'],
    image: null,
  },
  {
    key: 'bmw-i7-xdrive60',
    brand: 'BMW',
    name: 'i7 xDrive60',
    category: 'luxury',
    dailyRate: 249,
    weeklyRate: 1370,
    rangeEpa: 318,
    seats: 5,
    cargo: '18 cu ft',
    chargingSpeed: '195 kW DC',
    zerotoSixty: '4.5s',
    features: ['Theater screen 31"', 'Executive rear seats', 'Crystal controls'],
    image: null,
  },
  {
    key: 'bmw-i7-m70',
    brand: 'BMW',
    name: 'i7 M70',
    category: 'luxury',
    dailyRate: 299,
    weeklyRate: 1645,
    rangeEpa: 295,
    seats: 5,
    cargo: '18 cu ft',
    chargingSpeed: '195 kW DC',
    zerotoSixty: '3.5s',
    features: ['650 hp', 'Bowers & Wilkins 4D', 'Sky Lounge roof'],
    image: null,
  },
  {
    key: 'bmw-ix-xdrive40',
    brand: 'BMW',
    name: 'iX xDrive40',
    category: 'suv',
    dailyRate: 159,
    weeklyRate: 875,
    rangeEpa: 307,
    seats: 5,
    cargo: '77 cu ft',
    chargingSpeed: '150 kW DC',
    zerotoSixty: '6.1s',
    features: ['iDrive 8', 'Crystal headlights', 'Shy-Tech design'],
    image: null,
  },
  {
    key: 'bmw-ix-xdrive50',
    brand: 'BMW',
    name: 'iX xDrive50',
    category: 'suv',
    dailyRate: 189,
    weeklyRate: 1040,
    rangeEpa: 324,
    seats: 5,
    cargo: '77 cu ft',
    chargingSpeed: '195 kW DC',
    zerotoSixty: '4.4s',
    features: ['Sky Lounge roof', 'Bowers & Wilkins', 'Air suspension'],
    image: null,
  },
  {
    key: 'bmw-ix-m60',
    brand: 'BMW',
    name: 'iX M60',
    category: 'performance',
    dailyRate: 229,
    weeklyRate: 1260,
    rangeEpa: 288,
    seats: 5,
    cargo: '77 cu ft',
    chargingSpeed: '195 kW DC',
    zerotoSixty: '3.6s',
    features: ['M Sport brakes', '610 hp', 'Adaptive M suspension'],
    image: null,
  },

  // ─── Mercedes ───────────────────────────────────────────────────────────
  {
    key: 'mercedes-eqa',
    brand: 'Mercedes-Benz',
    name: 'EQA 250+',
    category: 'suv',
    dailyRate: 119,
    weeklyRate: 655,
    rangeEpa: 279,
    seats: 5,
    cargo: '51 cu ft',
    chargingSpeed: '100 kW DC',
    zerotoSixty: '7.7s',
    features: ['MBUX', 'AMG Line', 'Ambient lighting'],
    image: null,
  },
  {
    key: 'mercedes-eqb',
    brand: 'Mercedes-Benz',
    name: 'EQB 300',
    category: 'suv',
    dailyRate: 129,
    weeklyRate: 710,
    rangeEpa: 245,
    seats: 7,
    cargo: '62 cu ft',
    chargingSpeed: '100 kW DC',
    zerotoSixty: '6.2s',
    features: ['3-row seating', 'MBUX dual screen', 'AMG Line'],
    image: null,
  },
  {
    key: 'mercedes-eqe-sedan',
    brand: 'Mercedes-Benz',
    name: 'EQE Sedan 350+',
    category: 'luxury',
    dailyRate: 169,
    weeklyRate: 930,
    rangeEpa: 305,
    seats: 5,
    cargo: '14 cu ft',
    chargingSpeed: '170 kW DC',
    zerotoSixty: '5.9s',
    features: ['Hyperscreen option', 'Air Body Control', 'Burmester audio'],
    image: null,
  },
  {
    key: 'mercedes-eqe-suv',
    brand: 'Mercedes-Benz',
    name: 'EQE SUV 350+',
    category: 'suv',
    dailyRate: 179,
    weeklyRate: 985,
    rangeEpa: 279,
    seats: 5,
    cargo: '67 cu ft',
    chargingSpeed: '170 kW DC',
    zerotoSixty: '6.2s',
    features: ['MBUX Hyperscreen', 'Air suspension', 'HEPA filter'],
    image: null,
  },
  {
    key: 'mercedes-eqs-sedan',
    brand: 'Mercedes-Benz',
    name: 'EQS Sedan 450+',
    category: 'luxury',
    dailyRate: 249,
    weeklyRate: 1370,
    rangeEpa: 350,
    seats: 5,
    cargo: '22 cu ft',
    chargingSpeed: '200 kW DC',
    zerotoSixty: '5.3s',
    features: ['56" MBUX Hyperscreen', 'Rear axle steering', 'Energizing Comfort'],
    image: null,
  },
  {
    key: 'mercedes-eqs-suv',
    brand: 'Mercedes-Benz',
    name: 'EQS SUV 450+',
    category: 'luxury',
    dailyRate: 269,
    weeklyRate: 1480,
    rangeEpa: 305,
    seats: 7,
    cargo: '74 cu ft',
    chargingSpeed: '200 kW DC',
    zerotoSixty: '5.8s',
    features: ['MBUX Hyperscreen', '3-row luxury', 'E-Active Body Control'],
    image: null,
  },

  // ─── Audi ───────────────────────────────────────────────────────────────
  {
    key: 'audi-q4-etron',
    brand: 'Audi',
    name: 'Q4 e-tron',
    category: 'suv',
    dailyRate: 129,
    weeklyRate: 710,
    rangeEpa: 265,
    seats: 5,
    cargo: '53 cu ft',
    chargingSpeed: '175 kW DC',
    zerotoSixty: '5.8s',
    features: ['Virtual cockpit', 'MMI touch', 'Progressive steering'],
    image: null,
  },
  {
    key: 'audi-q8-etron',
    brand: 'Audi',
    name: 'Q8 e-tron',
    category: 'suv',
    dailyRate: 179,
    weeklyRate: 985,
    rangeEpa: 285,
    seats: 5,
    cargo: '57 cu ft',
    chargingSpeed: '170 kW DC',
    zerotoSixty: '5.4s',
    features: ['Air suspension', 'Bang & Olufsen 3D', 'Matrix LED'],
    image: null,
  },
  {
    key: 'audi-etron-gt',
    brand: 'Audi',
    name: 'e-tron GT',
    category: 'luxury',
    dailyRate: 219,
    weeklyRate: 1205,
    rangeEpa: 270,
    seats: 5,
    cargo: '13 cu ft',
    chargingSpeed: '270 kW DC',
    zerotoSixty: '3.9s',
    features: ['Air suspension', 'Matrix LED', 'Carbon roof'],
    image: null,
  },
  {
    key: 'audi-rs-etron-gt',
    brand: 'Audi',
    name: 'RS e-tron GT',
    category: 'performance',
    dailyRate: 269,
    weeklyRate: 1480,
    rangeEpa: 246,
    seats: 5,
    cargo: '13 cu ft',
    chargingSpeed: '270 kW DC',
    zerotoSixty: '3.1s',
    features: ['637 hp', 'Carbon ceramic brakes', 'Sport differential'],
    image: null,
  },

  // ─── Porsche ────────────────────────────────────────────────────────────
  {
    key: 'porsche-taycan',
    brand: 'Porsche',
    name: 'Taycan',
    category: 'luxury',
    dailyRate: 199,
    weeklyRate: 1095,
    rangeEpa: 246,
    seats: 5,
    cargo: '14 cu ft',
    chargingSpeed: '270 kW DC',
    zerotoSixty: '5.1s',
    features: ['Curved display', 'Porsche Active Suspension', 'Sport Chrono'],
    image: null,
  },
  {
    key: 'porsche-taycan-4s',
    brand: 'Porsche',
    name: 'Taycan 4S',
    category: 'performance',
    dailyRate: 229,
    weeklyRate: 1260,
    rangeEpa: 252,
    seats: 5,
    cargo: '14 cu ft',
    chargingSpeed: '270 kW DC',
    zerotoSixty: '3.8s',
    features: ['Performance Battery Plus', 'PASM', 'Sport Chrono'],
    image: null,
  },
  {
    key: 'porsche-taycan-gts',
    brand: 'Porsche',
    name: 'Taycan GTS',
    category: 'performance',
    dailyRate: 259,
    weeklyRate: 1425,
    rangeEpa: 246,
    seats: 5,
    cargo: '14 cu ft',
    chargingSpeed: '270 kW DC',
    zerotoSixty: '3.5s',
    features: ['GTS Sport Design', 'PDCC Sport', 'Rear axle steering'],
    image: null,
  },
  {
    key: 'porsche-taycan-turbo',
    brand: 'Porsche',
    name: 'Taycan Turbo',
    category: 'performance',
    dailyRate: 299,
    weeklyRate: 1645,
    rangeEpa: 238,
    seats: 5,
    cargo: '14 cu ft',
    chargingSpeed: '270 kW DC',
    zerotoSixty: '2.7s',
    features: ['680 hp', 'PDCC Sport', 'Burmester audio'],
    image: null,
  },
  {
    key: 'porsche-taycan-turbo-s',
    brand: 'Porsche',
    name: 'Taycan Turbo S',
    category: 'performance',
    dailyRate: 349,
    weeklyRate: 1920,
    rangeEpa: 222,
    seats: 5,
    cargo: '14 cu ft',
    chargingSpeed: '270 kW DC',
    zerotoSixty: '2.4s',
    features: ['750 hp', 'Carbon ceramic brakes', 'PDCC Sport'],
    image: null,
  },
  {
    key: 'porsche-taycan-cross-turismo',
    brand: 'Porsche',
    name: 'Taycan Cross Turismo',
    category: 'luxury',
    dailyRate: 219,
    weeklyRate: 1205,
    rangeEpa: 238,
    seats: 5,
    cargo: '42 cu ft',
    chargingSpeed: '270 kW DC',
    zerotoSixty: '4.8s',
    features: ['Off-road design', 'Gravel mode', 'Panoramic roof'],
    image: null,
  },

  // ─── Hyundai ────────────────────────────────────────────────────────────
  {
    key: 'hyundai-ioniq-5',
    brand: 'Hyundai',
    name: 'Ioniq 5',
    category: 'suv',
    dailyRate: 89,
    weeklyRate: 490,
    rangeEpa: 303,
    seats: 5,
    cargo: '60 cu ft',
    chargingSpeed: '350 kW DC',
    zerotoSixty: '5.2s',
    features: ['800V architecture', 'V2L power', 'Sliding console'],
    image: null,
  },
  {
    key: 'hyundai-ioniq-6',
    brand: 'Hyundai',
    name: 'Ioniq 6',
    category: 'sedan',
    dailyRate: 99,
    weeklyRate: 545,
    rangeEpa: 361,
    seats: 5,
    cargo: '12 cu ft',
    chargingSpeed: '350 kW DC',
    zerotoSixty: '5.1s',
    features: ['800V ultra-fast charging', 'Ambient pixel lights', 'Digital mirrors'],
    image: null,
  },

  // ─── Kia ────────────────────────────────────────────────────────────────
  {
    key: 'kia-ev6',
    brand: 'Kia',
    name: 'EV6',
    category: 'suv',
    dailyRate: 89,
    weeklyRate: 490,
    rangeEpa: 310,
    seats: 5,
    cargo: '50 cu ft',
    chargingSpeed: '350 kW DC',
    zerotoSixty: '5.1s',
    features: ['800V fast charging', 'V2L power', 'Dual curved screens'],
    image: null,
  },
  {
    key: 'kia-ev9',
    brand: 'Kia',
    name: 'EV9',
    category: 'suv',
    dailyRate: 129,
    weeklyRate: 710,
    rangeEpa: 304,
    seats: 7,
    cargo: '82 cu ft',
    chargingSpeed: '350 kW DC',
    zerotoSixty: '5.3s',
    features: ['3-row seating', 'Highway Driving Pilot', '27" triple display'],
    image: null,
  },

  // ─── Genesis ────────────────────────────────────────────────────────────
  {
    key: 'genesis-gv60',
    brand: 'Genesis',
    name: 'GV60',
    category: 'suv',
    dailyRate: 129,
    weeklyRate: 710,
    rangeEpa: 248,
    seats: 5,
    cargo: '54 cu ft',
    chargingSpeed: '350 kW DC',
    zerotoSixty: '4.0s',
    features: ['Crystal Sphere', 'Face recognition', 'Bang & Olufsen'],
    image: null,
  },
  {
    key: 'genesis-gv70e',
    brand: 'Genesis',
    name: 'Electrified GV70',
    category: 'suv',
    dailyRate: 149,
    weeklyRate: 820,
    rangeEpa: 236,
    seats: 5,
    cargo: '56 cu ft',
    chargingSpeed: '350 kW DC',
    zerotoSixty: '4.2s',
    features: ['Boost mode', 'e-Terrain mode', 'Lexicon audio'],
    image: null,
  },
  {
    key: 'genesis-gv80e',
    brand: 'Genesis',
    name: 'Electrified GV80',
    category: 'luxury',
    dailyRate: 179,
    weeklyRate: 985,
    rangeEpa: 307,
    seats: 7,
    cargo: '84 cu ft',
    chargingSpeed: '350 kW DC',
    zerotoSixty: '4.8s',
    features: ['3-row luxury', 'Air suspension', 'Bang & Olufsen 3D'],
    image: null,
  },

  // ─── Ford ───────────────────────────────────────────────────────────────
  {
    key: 'ford-mach-e-select',
    brand: 'Ford',
    name: 'Mustang Mach-E Select',
    category: 'suv',
    dailyRate: 99,
    weeklyRate: 545,
    rangeEpa: 250,
    seats: 5,
    cargo: '60 cu ft',
    chargingSpeed: '150 kW DC',
    zerotoSixty: '5.8s',
    features: ['SYNC 4A', '15.5" touchscreen', 'Phone as key'],
    image: null,
  },
  {
    key: 'ford-mach-e-premium',
    brand: 'Ford',
    name: 'Mustang Mach-E Premium',
    category: 'suv',
    dailyRate: 119,
    weeklyRate: 655,
    rangeEpa: 290,
    seats: 5,
    cargo: '60 cu ft',
    chargingSpeed: '150 kW DC',
    zerotoSixty: '4.8s',
    features: ['B&O audio', 'Panoramic roof', 'Hands-free driving'],
    image: null,
  },
  {
    key: 'ford-mach-e-gt',
    brand: 'Ford',
    name: 'Mustang Mach-E GT',
    category: 'performance',
    dailyRate: 149,
    weeklyRate: 820,
    rangeEpa: 270,
    seats: 5,
    cargo: '60 cu ft',
    chargingSpeed: '150 kW DC',
    zerotoSixty: '3.5s',
    features: ['480 hp', 'MagneRide damping', 'Performance brakes'],
    image: null,
  },
  {
    key: 'ford-f150-lightning-standard',
    brand: 'Ford',
    name: 'F-150 Lightning Standard',
    category: 'truck',
    dailyRate: 139,
    weeklyRate: 765,
    rangeEpa: 240,
    seats: 5,
    cargo: '52 cu ft bed',
    chargingSpeed: '150 kW DC',
    zerotoSixty: '4.0s',
    features: ['Pro Power Onboard', 'Mega frunk', 'BlueCruise'],
    image: null,
  },
  {
    key: 'ford-f150-lightning-extended',
    brand: 'Ford',
    name: 'F-150 Lightning Extended',
    category: 'truck',
    dailyRate: 169,
    weeklyRate: 930,
    rangeEpa: 320,
    seats: 5,
    cargo: '52 cu ft bed',
    chargingSpeed: '150 kW DC',
    zerotoSixty: '4.0s',
    features: ['Extended range battery', '131 kWh', 'Max tow 10,000 lbs'],
    image: null,
  },

  // ─── Chevrolet ──────────────────────────────────────────────────────────
  {
    key: 'chevrolet-bolt-ev',
    brand: 'Chevrolet',
    name: 'Bolt EV',
    category: 'sedan',
    dailyRate: 69,
    weeklyRate: 380,
    rangeEpa: 259,
    seats: 5,
    cargo: '57 cu ft',
    chargingSpeed: '55 kW DC',
    zerotoSixty: '6.5s',
    features: ['One-pedal driving', '10.2" touchscreen', 'Super Cruise ready'],
    image: null,
  },
  {
    key: 'chevrolet-bolt-euv',
    brand: 'Chevrolet',
    name: 'Bolt EUV',
    category: 'suv',
    dailyRate: 79,
    weeklyRate: 435,
    rangeEpa: 247,
    seats: 5,
    cargo: '57 cu ft',
    chargingSpeed: '55 kW DC',
    zerotoSixty: '7.0s',
    features: ['Super Cruise', 'Sunroof', 'Bose audio'],
    image: null,
  },
  {
    key: 'chevrolet-equinox-ev',
    brand: 'Chevrolet',
    name: 'Equinox EV',
    category: 'suv',
    dailyRate: 89,
    weeklyRate: 490,
    rangeEpa: 319,
    seats: 5,
    cargo: '57 cu ft',
    chargingSpeed: '150 kW DC',
    zerotoSixty: '5.9s',
    features: ['17.7" display', 'Super Cruise', 'Ultium platform'],
    image: null,
  },
  {
    key: 'chevrolet-silverado-ev',
    brand: 'Chevrolet',
    name: 'Silverado EV RST',
    category: 'truck',
    dailyRate: 179,
    weeklyRate: 985,
    rangeEpa: 400,
    seats: 5,
    cargo: '63 cu ft bed',
    chargingSpeed: '350 kW DC',
    zerotoSixty: '4.5s',
    features: ['Multi-Flex Midgate', 'CrabWalk', '24" display'],
    image: null,
  },

  // ─── GMC ────────────────────────────────────────────────────────────────
  {
    key: 'gmc-hummer-ev-truck',
    brand: 'GMC',
    name: 'Hummer EV Pickup',
    category: 'truck',
    dailyRate: 249,
    weeklyRate: 1370,
    rangeEpa: 329,
    seats: 5,
    cargo: '59 cu ft bed',
    chargingSpeed: '350 kW DC',
    zerotoSixty: '3.0s',
    features: ['CrabWalk', 'Extract Mode', '1,000 hp'],
    image: null,
  },
  {
    key: 'gmc-hummer-ev-suv',
    brand: 'GMC',
    name: 'Hummer EV SUV',
    category: 'suv',
    dailyRate: 239,
    weeklyRate: 1315,
    rangeEpa: 314,
    seats: 5,
    cargo: '81 cu ft',
    chargingSpeed: '350 kW DC',
    zerotoSixty: '3.5s',
    features: ['CrabWalk', 'Power rear drop glass', 'Infinity roof'],
    image: null,
  },
  {
    key: 'gmc-sierra-ev',
    brand: 'GMC',
    name: 'Sierra EV Denali',
    category: 'truck',
    dailyRate: 199,
    weeklyRate: 1095,
    rangeEpa: 440,
    seats: 5,
    cargo: '63 cu ft bed',
    chargingSpeed: '350 kW DC',
    zerotoSixty: '4.5s',
    features: ['MultiPro Tailgate', 'CrabWalk', '16.8" display'],
    image: null,
  },

  // ─── Cadillac ───────────────────────────────────────────────────────────
  {
    key: 'cadillac-lyriq',
    brand: 'Cadillac',
    name: 'Lyriq',
    category: 'luxury',
    dailyRate: 179,
    weeklyRate: 985,
    rangeEpa: 314,
    seats: 5,
    cargo: '60 cu ft',
    chargingSpeed: '190 kW DC',
    zerotoSixty: '5.5s',
    features: ['33" LED display', 'Super Cruise', 'AKG studio audio'],
    image: null,
  },
  {
    key: 'cadillac-optiq',
    brand: 'Cadillac',
    name: 'Optiq',
    category: 'suv',
    dailyRate: 149,
    weeklyRate: 820,
    rangeEpa: 300,
    seats: 5,
    cargo: '55 cu ft',
    chargingSpeed: '150 kW DC',
    zerotoSixty: '5.8s',
    features: ['33" display', 'Super Cruise', 'AKG audio'],
    image: null,
  },
  {
    key: 'cadillac-vistiq',
    brand: 'Cadillac',
    name: 'Vistiq',
    category: 'luxury',
    dailyRate: 199,
    weeklyRate: 1095,
    rangeEpa: 320,
    seats: 7,
    cargo: '76 cu ft',
    chargingSpeed: '190 kW DC',
    zerotoSixty: '5.3s',
    features: ['3-row luxury', 'Super Cruise', 'AKG Studio 3D'],
    image: null,
  },

  // ─── Volvo ──────────────────────────────────────────────────────────────
  {
    key: 'volvo-ex30',
    brand: 'Volvo',
    name: 'EX30',
    category: 'suv',
    dailyRate: 79,
    weeklyRate: 435,
    rangeEpa: 275,
    seats: 5,
    cargo: '44 cu ft',
    chargingSpeed: '153 kW DC',
    zerotoSixty: '5.1s',
    features: ['Minimalist interior', 'Harman Kardon', 'Sustainable materials'],
    image: null,
  },
  {
    key: 'volvo-ex40',
    brand: 'Volvo',
    name: 'EX40',
    category: 'suv',
    dailyRate: 109,
    weeklyRate: 600,
    rangeEpa: 254,
    seats: 5,
    cargo: '52 cu ft',
    chargingSpeed: '150 kW DC',
    zerotoSixty: '4.7s',
    features: ['Google built-in', 'Pilot Assist', 'Harman Kardon'],
    image: null,
  },
  {
    key: 'volvo-ec40',
    brand: 'Volvo',
    name: 'EC40',
    category: 'suv',
    dailyRate: 119,
    weeklyRate: 655,
    rangeEpa: 260,
    seats: 5,
    cargo: '49 cu ft',
    chargingSpeed: '150 kW DC',
    zerotoSixty: '4.5s',
    features: ['Coupe design', 'Google built-in', 'Pilot Assist'],
    image: null,
  },
  {
    key: 'volvo-ex90',
    brand: 'Volvo',
    name: 'EX90',
    category: 'luxury',
    dailyRate: 179,
    weeklyRate: 985,
    rangeEpa: 310,
    seats: 7,
    cargo: '74 cu ft',
    chargingSpeed: '250 kW DC',
    zerotoSixty: '4.9s',
    features: ['LiDAR standard', 'Bowers & Wilkins', 'Bidirectional charging'],
    image: null,
  },

  // ─── Polestar ───────────────────────────────────────────────────────────
  {
    key: 'polestar-2',
    brand: 'Polestar',
    name: 'Polestar 2',
    category: 'sedan',
    dailyRate: 109,
    weeklyRate: 600,
    rangeEpa: 320,
    seats: 5,
    cargo: '14 cu ft',
    chargingSpeed: '205 kW DC',
    zerotoSixty: '4.3s',
    features: ['Google built-in', 'Ohlins dampers option', 'Vegan interior'],
    image: null,
  },
  {
    key: 'polestar-3',
    brand: 'Polestar',
    name: 'Polestar 3',
    category: 'suv',
    dailyRate: 159,
    weeklyRate: 875,
    rangeEpa: 315,
    seats: 5,
    cargo: '67 cu ft',
    chargingSpeed: '250 kW DC',
    zerotoSixty: '4.6s',
    features: ['Dual motor', 'Air suspension', 'Bowers & Wilkins'],
    image: null,
  },
  {
    key: 'polestar-4',
    brand: 'Polestar',
    name: 'Polestar 4',
    category: 'suv',
    dailyRate: 149,
    weeklyRate: 820,
    rangeEpa: 300,
    seats: 5,
    cargo: '53 cu ft',
    chargingSpeed: '200 kW DC',
    zerotoSixty: '3.8s',
    features: ['No rear window', 'Rear camera mirror', 'Harman Kardon'],
    image: null,
  },

  // ─── Nissan ─────────────────────────────────────────────────────────────
  {
    key: 'nissan-ariya-2wd',
    brand: 'Nissan',
    name: 'Ariya Engage FWD',
    category: 'suv',
    dailyRate: 99,
    weeklyRate: 545,
    rangeEpa: 304,
    seats: 5,
    cargo: '59 cu ft',
    chargingSpeed: '130 kW DC',
    zerotoSixty: '7.2s',
    features: ['ProPILOT Assist 2.0', 'e-4ORCE ready', 'Zero-gravity seats'],
    image: null,
  },
  {
    key: 'nissan-ariya-awd',
    brand: 'Nissan',
    name: 'Ariya e-4ORCE AWD',
    category: 'suv',
    dailyRate: 109,
    weeklyRate: 600,
    rangeEpa: 272,
    seats: 5,
    cargo: '59 cu ft',
    chargingSpeed: '130 kW DC',
    zerotoSixty: '4.7s',
    features: ['e-4ORCE AWD', 'ProPILOT 2.0', 'Bose audio'],
    image: null,
  },

  // ─── Subaru ─────────────────────────────────────────────────────────────
  {
    key: 'subaru-solterra',
    brand: 'Subaru',
    name: 'Solterra',
    category: 'suv',
    dailyRate: 99,
    weeklyRate: 545,
    rangeEpa: 228,
    seats: 5,
    cargo: '53 cu ft',
    chargingSpeed: '150 kW DC',
    zerotoSixty: '6.5s',
    features: ['Symmetrical AWD', 'X-Mode', 'StarDrive technology'],
    image: null,
  },

  // ─── Toyota ─────────────────────────────────────────────────────────────
  {
    key: 'toyota-bz4x',
    brand: 'Toyota',
    name: 'bZ4X',
    category: 'suv',
    dailyRate: 89,
    weeklyRate: 490,
    rangeEpa: 252,
    seats: 5,
    cargo: '53 cu ft',
    chargingSpeed: '150 kW DC',
    zerotoSixty: '6.9s',
    features: ['Solar panel roof option', 'Toyota Safety Sense 3.0', 'AWD available'],
    image: null,
  },

  // ─── Lexus ──────────────────────────────────────────────────────────────
  {
    key: 'lexus-rz-450e',
    brand: 'Lexus',
    name: 'RZ 450e',
    category: 'luxury',
    dailyRate: 149,
    weeklyRate: 820,
    rangeEpa: 220,
    seats: 5,
    cargo: '50 cu ft',
    chargingSpeed: '150 kW DC',
    zerotoSixty: '4.8s',
    features: ['Direct4 AWD', 'Yoke steering option', 'Mark Levinson audio'],
    image: null,
  },
  {
    key: 'lexus-rz-300e',
    brand: 'Lexus',
    name: 'RZ 300e',
    category: 'suv',
    dailyRate: 129,
    weeklyRate: 710,
    rangeEpa: 266,
    seats: 5,
    cargo: '50 cu ft',
    chargingSpeed: '150 kW DC',
    zerotoSixty: '7.5s',
    features: ['FWD efficiency', 'Lexus Interface', 'Mark Levinson'],
    image: null,
  },

  // ─── Honda ──────────────────────────────────────────────────────────────
  {
    key: 'honda-prologue',
    brand: 'Honda',
    name: 'Prologue',
    category: 'suv',
    dailyRate: 109,
    weeklyRate: 600,
    rangeEpa: 296,
    seats: 5,
    cargo: '72 cu ft',
    chargingSpeed: '150 kW DC',
    zerotoSixty: '5.7s',
    features: ['Google built-in', 'Ultium platform', 'Panoramic roof'],
    image: null,
  },

  // ─── Acura ──────────────────────────────────────────────────────────────
  {
    key: 'acura-zdx',
    brand: 'Acura',
    name: 'ZDX',
    category: 'suv',
    dailyRate: 149,
    weeklyRate: 820,
    rangeEpa: 313,
    seats: 5,
    cargo: '70 cu ft',
    chargingSpeed: '190 kW DC',
    zerotoSixty: '5.7s',
    features: ['ELS Studio 3D', 'AcuraLink', 'Precision handling'],
    image: null,
  },

  // ─── Lucid ──────────────────────────────────────────────────────────────
  {
    key: 'lucid-air-pure',
    brand: 'Lucid',
    name: 'Air Pure',
    category: 'luxury',
    dailyRate: 199,
    weeklyRate: 1095,
    rangeEpa: 419,
    seats: 5,
    cargo: '32 cu ft',
    chargingSpeed: '300 kW DC',
    zerotoSixty: '3.8s',
    features: ['Glass Canopy roof', 'Surreal Sound', '34" curved display'],
    image: null,
  },
  {
    key: 'lucid-air-touring',
    brand: 'Lucid',
    name: 'Air Touring',
    category: 'luxury',
    dailyRate: 249,
    weeklyRate: 1370,
    rangeEpa: 425,
    seats: 5,
    cargo: '32 cu ft',
    chargingSpeed: '300 kW DC',
    zerotoSixty: '3.4s',
    features: ['DreamDrive Pro', 'Surreal Sound Pro', 'Nappa leather'],
    image: null,
  },
  {
    key: 'lucid-air-grand-touring',
    brand: 'Lucid',
    name: 'Air Grand Touring',
    category: 'luxury',
    dailyRate: 299,
    weeklyRate: 1645,
    rangeEpa: 516,
    seats: 5,
    cargo: '32 cu ft',
    chargingSpeed: '300 kW DC',
    zerotoSixty: '3.0s',
    features: ['1,050 hp', '500+ mi range', 'DreamDrive Pro'],
    image: null,
  },
  {
    key: 'lucid-air-sapphire',
    brand: 'Lucid',
    name: 'Air Sapphire',
    category: 'performance',
    dailyRate: 399,
    weeklyRate: 2195,
    rangeEpa: 427,
    seats: 5,
    cargo: '32 cu ft',
    chargingSpeed: '300 kW DC',
    zerotoSixty: '1.89s',
    features: ['1,234 hp tri-motor', 'Carbon ceramic brakes', 'Track-tuned suspension'],
    image: null,
  },

  // ─── Fisker ─────────────────────────────────────────────────────────────
  {
    key: 'fisker-ocean-sport',
    brand: 'Fisker',
    name: 'Ocean Sport',
    category: 'suv',
    dailyRate: 89,
    weeklyRate: 490,
    rangeEpa: 250,
    seats: 5,
    cargo: '57 cu ft',
    chargingSpeed: '125 kW DC',
    zerotoSixty: '6.9s',
    features: ['California mode', 'Recycled materials', '17.1" display'],
    image: null,
  },
  {
    key: 'fisker-ocean-ultra',
    brand: 'Fisker',
    name: 'Ocean Ultra',
    category: 'suv',
    dailyRate: 109,
    weeklyRate: 600,
    rangeEpa: 340,
    seats: 5,
    cargo: '57 cu ft',
    chargingSpeed: '200 kW DC',
    zerotoSixty: '3.9s',
    features: ['AWD', 'SolarSky roof', 'California mode'],
    image: null,
  },
  {
    key: 'fisker-ocean-extreme',
    brand: 'Fisker',
    name: 'Ocean Extreme',
    category: 'suv',
    dailyRate: 129,
    weeklyRate: 710,
    rangeEpa: 360,
    seats: 5,
    cargo: '57 cu ft',
    chargingSpeed: '200 kW DC',
    zerotoSixty: '3.6s',
    features: ['SolarSky roof', 'Revolve rotating screen', '22" wheels'],
    image: null,
  },

  // ─── MINI ───────────────────────────────────────────────────────────────
  {
    key: 'mini-cooper-se',
    brand: 'MINI',
    name: 'Cooper SE',
    category: 'sedan',
    dailyRate: 79,
    weeklyRate: 435,
    rangeEpa: 114,
    seats: 4,
    cargo: '8.7 cu ft',
    chargingSpeed: '50 kW DC',
    zerotoSixty: '6.9s',
    features: ['Go-kart handling', 'OLED display', 'Union Jack taillights'],
    image: null,
  },
  {
    key: 'mini-countryman-e',
    brand: 'MINI',
    name: 'Countryman Electric',
    category: 'suv',
    dailyRate: 89,
    weeklyRate: 490,
    rangeEpa: 245,
    seats: 5,
    cargo: '47 cu ft',
    chargingSpeed: '130 kW DC',
    zerotoSixty: '5.6s',
    features: ['ALL4 AWD', 'OLED cockpit', 'Charismatic mode'],
    image: null,
  },

  // ─── Jaguar ─────────────────────────────────────────────────────────────
  {
    key: 'jaguar-i-pace',
    brand: 'Jaguar',
    name: 'I-PACE',
    category: 'luxury',
    dailyRate: 169,
    weeklyRate: 930,
    rangeEpa: 246,
    seats: 5,
    cargo: '51 cu ft',
    chargingSpeed: '100 kW DC',
    zerotoSixty: '4.5s',
    features: ['Pivi Pro', 'Air suspension', 'Meridian 3D audio'],
    image: null,
  },
];

// ── Derived Exports ─────────────────────────────────────────────────────────

export const BRANDS: string[] = [
  ...new Set(FLEET.map((v) => v.brand)),
].sort((a, b) => a.localeCompare(b));

export const CATEGORIES: Vehicle['category'][] = [
  'sedan',
  'suv',
  'truck',
  'luxury',
  'performance',
];

// ── Helpers ─────────────────────────────────────────────────────────────────

export function getVehicleByKey(key: string): Vehicle | undefined {
  return FLEET.find((v) => v.key === key);
}

export function filterFleet(filters: FleetFilters): Vehicle[] {
  let results = FLEET;

  if (filters.category && filters.category !== 'all') {
    results = results.filter((v) => v.category === filters.category);
  }

  if (filters.brand) {
    results = results.filter((v) => v.brand === filters.brand);
  }

  if (filters.priceRange) {
    switch (filters.priceRange) {
      case 'low':
        results = results.filter((v) => v.dailyRate < 100);
        break;
      case 'mid':
        results = results.filter((v) => v.dailyRate >= 100 && v.dailyRate < 200);
        break;
      case 'high':
        results = results.filter((v) => v.dailyRate >= 200);
        break;
    }
  }

  if (filters.minSeats) {
    results = results.filter((v) => v.seats >= filters.minSeats!);
  }

  if (filters.search) {
    const q = filters.search.toLowerCase();
    results = results.filter(
      (v) =>
        v.brand.toLowerCase().includes(q) ||
        v.name.toLowerCase().includes(q) ||
        v.key.toLowerCase().includes(q),
    );
  }

  return results;
}
