-- ═══════════════════════════════════════════════════════════════════════════
-- DEPRECATED — This file is superseded by:
--   supabase/migrations/001_core_schema.sql
--
-- Run the migration file in Supabase Dashboard → SQL Editor.
-- ═══════════════════════════════════════════════════════════════════════════
